### ISSUE TITLE
Add support for UI themes/skins to Pàdé Converse

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/Pade#103]
At the moment, Pàdé Converse has only a single UI theme/skin (black ink and white paper). Enable third-party themes/skins to be added via CSS by doing the following:

- Add a new option to allow named themes to be selected.
- Add same named css files to the plugins/css folder
- Add code to dynamically load the selected css file after the main converse.css file when starting Converse.

**Comment by jcbrand** [comment]
Converse supports theming via CSS properties.

https://conversejs.org/docs/html/configuration.html#theme

There's no UI for choosing a theme though, it would be great to have one ;)

**Comment by deleolajide** [comment]
>There's no UI for choosing a theme though, it would be great to have one ;)

Unfortunately, I am reusing the Browser Extension options UI for this and that will not translate into reuse directly from Converse. The CSS variables however, have been very useful in creating new themes with CSS that overrides converse.css.

**Comment by deleolajide** [comment]
This in now available in version 0.8.8.

There are 4 themes to choose from. 

![image](https://user-images.githubusercontent.com/110731/49901927-73e99600-fe5a-11e8-9ddf-8fb0b54ee7ce.png)

![image](https://user-images.githubusercontent.com/110731/49901899-5ae0e500-fe5a-11e8-80f4-11ed454ce6c9.png)

Add a new theme/skin involves a PR with new CSS file and a modification to append the theme/skin name to the UI list in manifest.js
