### ISSUE TITLE
Select messages in chat and email it 

### ISSUE THREAD

**Issue by rodrigolzd** [igniterealtime/Pade#106]
Add option to select individual or all messages and email them to yourself of any email. This would be helpful in situations where you discussed something important enough that leaving it in the chat log might now be the best option. 

Another good option would be to just select some of the messages and then hit copy to the clipboard from the menu. This would avoid having to copy individual messages several times and it would make easier to keep notes/logs with less clutter.

**Comment by marclaporte** [comment]
Other ideas:
* Copy to a task or wiki page
* Forward to another XMPP contact or to a room

Different but related task: Each message should be bookmarkable
Ex.: https://irc.tiki.org/irclogger_log/tikiwiki?date=2019-01-22,Tue&sel=92#l88

**Comment by deleolajide** [comment]
>Copy to a task or wiki page

See https://github.com/igniterealtime/Pade/issues/133

![image](https://user-images.githubusercontent.com/110731/54559442-fdf44e00-49b7-11e9-8b47-a0feb225632f.png)


>Each message should be bookmarkable

See https://github.com/conversejs/converse.js/issues/1497

**Comment by deleolajide** [comment]
>Add option to select individual or all messages and email them to yourself of any email.

There are many ways to do this, but the path of least resistance for me is to use a modal window to set the start and end time stamps and then make a REST call to the Openfire Chat API plugin to extract the conversation, create a PDF file and use the mailto: URI to post it by email

**Comment by rodrigolzd** [comment]
It is cool to create a pdf as well, but I don’t know if I would want a pdf all the time. Mostly I would like to have it as searchable and editable text. 

As you suggested it seems that it would create a block with start and end time stamps. So if I want to be picky and not save all other messages in that timeframe I would have to send multiple emails., and in some large rooms that might be chats that overlap, I think selecting individual messages and email them as text would be better.

Would it use the server as the mail provider or would the user have to use some other server?

**Comment by deleolajide** [comment]
>I think selecting individual messages and email them as text would be better.

It would be better, but it will be challenging to do the the UI for cherry picking messages. Personally, I would prefer to read all messages within a time-frame for context when viewing much later in the future.

>Mostly I would like to have it as searchable and editable text.

Best tool at the moment would be standard browser search (CTRL F), select text, copy (CTRL C) and paste (CTRL V)

**Comment by rodrigolzd** [comment]
Shouldnt these features be available in converse rather than pade?

**Comment by deleolajide** [comment]
>Shouldnt these features be available in converse rather than pade?

Probably, but I suspect that the real feature you need for taking notes and creating tasks during groupchat is existing issue  https://github.com/igniterealtime/Pade/issues/119

**Comment by deleolajide** [comment]
I consider this issue to be same as #195
