### ISSUE TITLE
"Leave this groupchat" removes me, but I am back in the room the next I time I load Pàdé

### ISSUE THREAD

**Issue by marclaporte** [igniterealtime/Pade#110]
![2019-01-03_191303](https://user-images.githubusercontent.com/1004261/50668215-b13dd100-0f8b-11e9-92ca-92520d1bc4a5.png)

**Comment by deleolajide** [comment]
In order to stop the auto-join at startup, try to delete the bookmark created as well. Please note that a bookmark created by the openfire bookmark plugin cannot be delete by Pàdé.

**Comment by deleolajide** [comment]
What happens when you remove the bookmark as well

![image](https://user-images.githubusercontent.com/110731/50902561-19b90200-1413-11e9-9f04-04541b139641.png)

**Comment by deleolajide** [comment]
Unable to reproduce. Please re-open if it still happens with version 0.9.2.
