### ISSUE TITLE
Separate port number from server address

### ISSUE THREAD

**Issue by rodrigolzd** [igniterealtime/Pade#113]
Divide the server address into two boxes.

In the Port number the default value should be 7443, even if its just cleared later on, but overwritten if any other number is  put in.

This will not conflict with the fact that the port number is mandatory, and it will help end users to enter the information, including when calling some tech support.

![pade-server-port](https://user-images.githubusercontent.com/4949495/50911993-3277e680-1418-11e9-930c-a65325d433ea.png)

**Comment by deleolajide** [comment]
The UI framework used in options does not allow for multiple data fields on the same line. As this field is only used in pade@work for generic use and is pre-configured and hidden in customer implementations, server address will remain as it is.
