### ISSUE TITLE
Support for automatically setting chat status

### ISSUE THREAD

**Issue by GregDThomas** [igniterealtime/Pade#123]
Would it be possible to add a support for automatically setting a status. I thinking of something like:

When chat window is opened, set status to: [Online] (selected from drop down list or similar)
When chat window is closed, set status to: [Away for long]

**Comment by deleolajide** [comment]
There is automatic presence status based on using [chrome.idle](https://developers.chrome.com/extensions/idle) that tracks overall desktop activity. It detects when desktop is active, idle or locked and I translate that into XMPP presence.

There is a **Do not Disturb** option in the context menu that disables all notifications and sets presence to "dnd".

![image](https://user-images.githubusercontent.com/110731/53639313-c009d280-3c20-11e9-8674-dc016d35b4ad.png)

There is a new feature in unreleased version 1.0.5 that allows a default presence status to always be set at login time.

![image](https://user-images.githubusercontent.com/110731/53639075-280be900-3c20-11e9-9038-19301efd3fe7.png)

I however suspect that these options are not exactly what you are asking for. A presence status for when the Converse chat window is opened and closed should be relatively easy to add.

**Comment by deleolajide** [comment]
Done. It should be available in 1.0.5 

![image](https://user-images.githubusercontent.com/110731/53641640-7ec8f100-3c27-11e9-8e26-df2bd84ca294.png)
