### ISSUE TITLE
Поддержка вкладок бесед (Conversation tab support)

### ISSUE THREAD

**Issue by AGNaumov** [igniterealtime/Pade#124]
Очень не хватает вкладок бесед (в spark web функция вкладок бесед реализована, это очень удобно если ведешь диалог с несколькими собеседниками).
Поведение вкладок может быть примерно такое:
- Вкладка беседы автоматически добавляться при новом сообщении от собеседника если вкладка беседы с ним не открыта.
- Открытая вкладка беседы подсвечивается (или как то выделяется) при новом сообщении, если она в момент поступления сообщения не выбрана (не активна).
- При запуски Pade открываются вкладки которые были открыты при закрытии программы.
- Также можно добавить настраиваемую вкладку по умолчанию в которой будет открываться ссылка на web страницу предварительно заданную в настройках.

Google translation by translator:
There are not enough conversation tabs (in the spark web, the conversation tab function is implemented, it is very convenient if you are conducting a dialogue with several interlocutors).
Tab behavior can be something like this:
- Conversations tab automatically added with a new message from the interlocutor if the conversation tab with him is not open.
- The open tab of the conversation is highlighted (or as it is highlighted) with a new message, if it is not selected (not active) at the time of receipt of the message.
- When Pade starts, the tabs open that were opened when the program was closed.
- You can also add a custom tab by default in which a link to the web page pre-specified in the settings will open.

**Comment by deleolajide** [comment]
There is no plan to add tabs to Pade. There is discussion to add a sorted list based on activity like Whatsapp, Skype, Hangouts and Facebook Messenger to Converse  at discuss@conference.conversejs.org

There is a feature in Pade to add a list of groupchats and chat jids to open at startup. What I can do is to automatically update this list when the Converse chat window closes based on activity.

![image](https://user-images.githubusercontent.com/110731/53698268-1d915100-3dd2-11e9-9643-88220866586c.png)

**Comment by AGNaumov** [comment]
Без вкладок бесед использование приложения в корпоративном сегменте, маловероятно. Whatsapp, Skype, Hangouts and Facebook Messenger - прежде всего ориентированы на частное использование. 
Google translation by translator:
Without conversation tabs, using the application in the corporate segment is unlikely. Whatsapp, Skype, Hangouts and Facebook Messenger are primarily for private use.

**Comment by deleolajide** [comment]
>Without conversation tabs, using the application in the corporate segment is unlikely

From my experience so far, users in the corporate segment want flexibility. They want both the ability to have tabbed conversation windows and also the ability to pop the chat windows out into standalone windows if needed like Skype for Business does. [Converse does that with the overlay mode](https://conversejs.org/), but Pade does not support that mode.

Pade has adopted the full-screen mode of Converse which has been made popular by [Slack](https://slack.com/features). It is a tabbed UI, but it is a vertical tab unlike the horizontal tab UI of a web browser.

If you really want the horizontal tab UI for XMPP like Spark does, take a look at  [Candy Chat](http://candy-chat.github.io/candy/) and the [candy chat plugin for openfire](https://github.com/igniterealtime/openfire-candy-plugin).

**Comment by AGNaumov** [comment]
> > Without conversation tabs, using the application in the corporate segment is unlikely
> 
> From my experience so far, users in the corporate segment want flexibility. They want both the ability to have tabbed conversation windows and also the ability to pop the chat windows out into standalone windows if needed like Skype for Business does. [Converse does that with the overlay mode](https://conversejs.org/), but Pade does not support that mode.
> 
> Pade has adopted the full-screen mode of Converse which has been made popular by [Slack](https://slack.com/features). It is a tabbed UI, but it is a vertical tab unlike the horizontal tab UI of a web browser.
> 
> If you really want the horizontal tab UI for XMPP like Spark does, take a look at [Candy Chat](http://candy-chat.github.io/candy/) and the [candy chat plugin for openfire](https://github.com/igniterealtime/openfire-candy-plugin).

Candy Chat не совсем подходит, на сколько я понял Candy Chat разработан для общения в груповых чатах. Вертикальные или горизонтальные вкладки не столь важно, важно чтобы список контактов и вкладки бесед размещались в разных местах, а не были одним списком. Список контактов может быть например как у меня более 100 собеседников, а список активных бесед в какойто определенный промежуток времени от двух до пяти. Постоянно прокручивать список более ста контактов чтоб переключаться между двумя или пятью собеседниками, очень неудобно.
Как пример в компании есть сервер Openfire который получает список пользователей из AD в Openfire настроен список контактов и групп который загружается всем пользователям при подключении к серверу. В этом списке может быть очень много контактов, все зависит от размеров компании. При этом активно переписываться пользователь может только с несколькими контактами из общего списка контактов.

Google translation by translator:

Candy Chat is not quite suitable, as far as I understand Candy Chat is designed to communicate in group chats. Vertical or horizontal tabs are not so important, it is important that the contact list and conversation tabs are located in different places, rather than being the same list. The list of contacts can be, for example, as I have more than 100 interlocutors, and the list of active conversations in a certain period of time from two to five. Constantly scroll through the list of more than a hundred contacts to switch between two or five interlocutors, it is very inconvenient.
As an example, the company has an Openfire server that receives a list of users from AD in Openfire is configured with a list of contacts and groups that is downloaded to all users when connected to the server. There can be a lot of contacts in this list, it all depends on the size of the company. At the same time, the user can actively communicate with only a few contacts from the general contact list.

**Comment by deleolajide** [comment]
>The list of contacts can be, for example, as I have more than 100 interlocutors, and the list of active conversations in a certain period of time from two to five. Constantly scroll through the list of more than a hundred contacts to switch between two or five interlocutors, it is very inconvenient.

Ok. I think I now understand the requirement. You need a list of active conversations in the UI. 
That is on my todo list, but I can take a look to see what can be done now.

**Comment by deleolajide** [comment]
Fixed in version 1.0.7
There is now an icon for a list of active conversations

![image](https://user-images.githubusercontent.com/110731/53770371-bad5ad80-3ed6-11e9-9341-f4187b43951c.png)

**Comment by AGNaumov** [comment]
> Fixed in version 1.0.7
> There is now an icon for a list of active conversations
> 
> ![image](https://user-images.githubusercontent.com/110731/53770371-bad5ad80-3ed6-11e9-9341-f4187b43951c.png)

Pade - Unified Communications at Work update to version 1.0.7 in the online store chrome is currently not (Обновление Pade - Unified Communications at Work до версии 1.0.7 в интернет-магазин chrome на данный момент нет)

**Comment by AGNaumov** [comment]
Thank you so much for the list of assets. (Огромное спасибо за список актив)

**Comment by AGNaumov** [comment]
As addition
Change the selection color of the interlocutor when you hover the mouse pointer in the UI Theme Fly Concord and add the ability to close the tab of one of the interlocutors when the conversation with him is over.

Как дополнение
Изменить цвет выделения собеседника при наведении указателя мышки в  UI Theme Fly Concord и добавить возможность закрыть вкладку одного из собеседников когда беседа с ним окончена.

**Comment by deleolajide** [comment]
There is more work to be done to the active conversations view and that will be done over time like sorting, time stamp, last message. For now, use the chatbox close and chatroom leave icons and refresh view. See below

![image](https://user-images.githubusercontent.com/110731/53801270-a32e1180-3f36-11e9-92ad-bd5a46f15719.png)

![image](https://user-images.githubusercontent.com/110731/53801297-b7720e80-3f36-11e9-9721-2965374f63f5.png)

**Comment by AGNaumov** [comment]
Please add the button "Remove from active conversations" (Добавьте пожалуйста кнопку "Убрать из активных разговоров")
![image](https://user-images.githubusercontent.com/48155843/54071923-37390980-42a6-11e9-85fd-6e101a03b536.png)
Then after the end of the conversation, you can remove the interlocutor from this list (Тогда после окончания разговора можно будет убрать собеседника из этого списка)

Please change the color of the selection of the interlocutor when you hover the mouse pointer in the UI Theme Fly Concord (Измените пожалуйста цвет выделения собеседника при наведении указателя мышки в UI Theme Fly Concord)

**Comment by deleolajide** [comment]
More work done on this for version 1.0.8

![image](https://user-images.githubusercontent.com/110731/54263083-e0faed80-4567-11e9-9808-dd7d158fbc58.png)

**Comment by AGNaumov** [comment]
> More work done on this for version 1.0.8
> 
> ![image](https://user-images.githubusercontent.com/110731/54263083-e0faed80-4567-11e9-9808-dd7d158fbc58.png)

Огромное спасибо. 

У меня есть ещё одна просьба.
Подправьте пожалуйста UI Theme Fly Concord цвет выделения собеседника при наведении указателя мышки на вкладке Active Conversations аналогично выделению собеседника при наведении указателя мышки основного списка контактов.

Google translation by translator:

Thank you so much.

I have another request.
Please correct the UI Theme Fly Concord color of the selection of the interlocutor when you hover the mouse over the tab Active Conversations is similar to the selection of the interlocutor when you hover the mouse over the main contact list.

**Comment by deleolajide** [comment]
Available in version 1.0.9

![image](https://user-images.githubusercontent.com/110731/54346570-394fef00-463d-11e9-8c4d-64dc9a71f7bc.png)

**Comment by AGNaumov** [comment]
> Available in version 1.0.9
> 
> ![image](https://user-images.githubusercontent.com/110731/54346570-394fef00-463d-11e9-8c4d-64dc9a71f7bc.png)

В магазине пока версия 1.08. Но судя по картинке нужно еще при наведении указателя мышки на вкладке Active Conversations в UI Theme Fly Concord менять цвет надписи (ника) на чёрный аналогично выделению собеседника при наведении указателя мышки основного списка контактов.

Google translation by translator:

In the store, version 1.08. Is still available. But judging by the picture, you need to change the color of the inscription (nickname) to black when you move the mouse pointer on the Active Conversations tab in the UI Theme Fly Concord.

**Comment by deleolajide** [comment]
>But judging by the picture, you need to change the color of the inscription (nickname) to black when you move the mouse pointer on the Active Conversations tab in the UI Theme Fly Concord.

I am  not good with CSS. I am using a single background color that works with all themes. A pull request (PR) is most welcome to fix it properly by any UI expert :-)

**Comment by AGNaumov** [comment]
Thank you so much
