### ISSUE TITLE
Bugs in version 1.0.6

### ISSUE THREAD

**Issue by AGNaumov** [igniterealtime/Pade#125]
- Уведомление о новом сообщение при свернутом pade само закрывается, перейти из уведомления в окно сообщения не получается. очень неудобно искать кто тебе написал.

Google translation by translator:

- Notification of a new message when the pade is minimized closes itself, it is not possible to switch from the notification to the message window. It is very inconvenient to search for who wrote to you.

**Comment by deleolajide** [comment]
>Each time you start a group chat lobby is automatically created.

It is deliberate. The purpose for first time users (especially anonymous users) with no bookmarks. It is to provide at least one open room for discussion. I will change the behavior for anonymous users only.

**Comment by deleolajide** [comment]
>The notification of a new message when the pade is minimized closes itself, it is not possible to switch from the notification to the message window. It is very inconvenient to search for who wrote to you.

There are 2 notification messages

![image](https://user-images.githubusercontent.com/110731/53698358-83caa380-3dd3-11e9-8aaf-2438d7a97235.png)

The first one is from Converse and does the behavior you described. It will disappear after 30 secs or less. The second one is from Pade and will remain until you click **view** or **ignore**.  Use the second one. Also make sure you enable notifications in preferences/settings.

**Comment by deleolajide** [comment]
>Does not save the position and size of the window (in the settings of the jackdaw set)

**Disclaimer here** It is very experimental and depend on your O/S as well as the type of monitors/screens you use. It may work or not work for you. use at your own risk.

**Comment by deleolajide** [comment]
>Each time you enter a group chat, it sends a message that the user has entered the room (the checkboxes in the settings are turned off)

Use this preference/setting

![image](https://user-images.githubusercontent.com/110731/53698429-7a8e0680-3dd4-11e9-8c0a-f4220227f4e2.png)

**Comment by AGNaumov** [comment]
> > The notification of a new message when the pade is minimized closes itself, it is not possible to switch from the notification to the message window. It is very inconvenient to search for who wrote to you.
> 
> There are 2 notification messages
> 
> ![image](https://user-images.githubusercontent.com/110731/53698358-83caa380-3dd3-11e9-8aaf-2438d7a97235.png)
> 
> The first one is from Converse and does the behavior you described. It will disappear after 30 secs or less. The second one is from browser extension background web page and will remain until you click **view** or **ignore**. Use the second one. Also make sure you enable notifications in preferences/settings.

В версии 1.0.5  уведомление с кнопкой "View" если pade свернут не появляется при обычном сообщении. При сообщении в групповом чате уведомление с кнопкой "View" если pade свернут появляется. Если закрыть окно pade уведомление с кнопкой "View" появляется в обоих случаях. Если это поведение зависит от настроек, подскажите пожалуйста какие настройки нужно включить.
Google translation by translator:
In version 1.0.5, a notification with the "View" button if the pade is minimized does not appear with a normal message. When you post in a group chat, a notification with the "View" button if the pade is minimized appears. If you close the pade window, a notification with the "View" button appears in both cases. If this behavior depends on the settings, please tell me what settings you need to enable.

**Comment by AGNaumov** [comment]
> > Each time you start a group chat lobby is automatically created.
> 
> It is deliberate. The purpose for first time users (especially anonymous users) with no bookmarks. It is to provide at least one open room for discussion. I will change the behavior for anonymous users only.

Можно сделать настройку для отключения этой опции. В случаи если сервер не публичный, создание комнат с групповыми чатами может быть запрещено.
Google translation by translator:
You can make a setting to disable this option. In cases where the server is not public, the creation of rooms with group chats may be prohibited.

**Comment by AGNaumov** [comment]
Может причина разного поведения заключается в том что я использую Pade - Unified Communications at Work?
Google translation by translator:
Maybe the reason for the different behavior is that I use Pade - Unified Communications at Work?

**Comment by deleolajide** [comment]
>You can make a setting to disable this option. In cases where the server is not public, the creation of rooms with group chats may be prohibited

It is easy to remove it completely. However, you may need to edit your preferences to remove the lobby room

![image](https://user-images.githubusercontent.com/110731/53724433-c6d35800-3e61-11e9-90b7-d1e58a1653a4.png)
