### ISSUE TITLE
Errors related to notifications in version 1.0.6 (Ошибки связанные с уведомлениями в версии 1.0.6)

### ISSUE THREAD

**Issue by AGNaumov** [igniterealtime/Pade#127]
Notifications about messages in group chat (Уведомления о сообщениях в групповом чате)
Notification with a button to view the message does not appear (Уведомление с кнопкой посмотреть сообщение не появляется)
![image](https://user-images.githubusercontent.com/48155843/53721949-f8b2e180-3e96-11e9-9a38-8d33f4b3da12.png)
![image](https://user-images.githubusercontent.com/48155843/53722069-462f4e80-3e97-11e9-87ec-d5af33f6df3d.png)
If the application minimized notification appears and you can go with it in the message (Если приложение свернуто уведомление появляется и можно с него перейти в сообщение)
![image](https://user-images.githubusercontent.com/48155843/53722197-93132500-3e97-11e9-9142-c8173d87a681.png)

User Message Notifications
Notification with a button to view the message does not appear (Уведомление с кнопкой посмотреть сообщение не появляется)
![image](https://user-images.githubusercontent.com/48155843/53722900-1ed98100-3e99-11e9-91b1-7ae224620706.png)
If the application minimized the notification disappears after 30 seconds, the notification with the button to see the message does not appear (Если приложение свернуто уведомление исчезает через 30 сек, уведомление с кнопкой посмотреть сообщение не появляется)
![image](https://user-images.githubusercontent.com/48155843/53723102-90193400-3e99-11e9-99c1-5284d6a540e8.png)

**Comment by deleolajide** [comment]
Thank you for the screenshots and explanation. I do a lot of groupchat and few contacts. I don't have this issue as I keep the chat window minimized and open only to respond to a notification and then minimized again.

Let me see what can be done :-)

**Comment by deleolajide** [comment]
This is now fixed in version 1.0.7
Notifications now always has a button to join conversation

**Comment by AGNaumov** [comment]
> This is now fixed in version 1.0.7
> Notifications now always has a button to join conversation

Pade - Unified Communications at Work update to version 1.0.7 in the online store chrome is currently not

**Comment by AGNaumov** [comment]
Thank you so much, in version 1.0.7, notifications work. (Огромное спасибо, в версии 1.0.7 уведомления работают)
