### ISSUE TITLE
Would this work with ejabberd??

### ISSUE THREAD

**Issue by stevenroose** [igniterealtime/Pade#128]
Hi, I saw your talk at FOSDEM and I am interested in testing this on our ejabberd server. I will be setting up Jisti Meet anyway, but can't test for now. Are there any aspects you know would not work with ejabberd?

**Comment by deleolajide** [comment]
In theory, it should work.

Most features are hidden behind settings/preferences with a default value to disable the feature and should not show up in the Converse conversation toolbar.

You don't need to setup Jitsi-Meet server-side as you can change the meeting base URL to https://meet.jit.si/ and use the hosted service instead for the embedded client code.

There are a few features that will rely on an Openfire plugin to do the server-side heavy lifting. They are mostly in the Applications section of the preferences UI. For example,

![image](https://user-images.githubusercontent.com/110731/53733468-f93c7f80-3e78-11e9-9778-8ae857c1832c.png)

Please advise me of any default settings that does break or cause a conflict with ejabberd.

**Comment by licaon-kter** [comment]
Works ok, at least the Converse part. :+1: 

Hope some of these visual changes end up upstream too.

**Comment by deleolajide** [comment]
> Hope some of these visual changes end up upstream too.

See https://github.com/conversejs/converse.js/issues/1349
See https://github.com/conversejs/converse.js/issues/1497
See https://github.com/conversejs/converse.js/issues/1329

**Comment by licaon-kter** [comment]
Thanks for the plugins link, not sure I ever saw that mentioned.
