### ISSUE TITLE
When the computer restarts, the pade runs twice

### ISSUE THREAD

**Issue by AGNaumov** [igniterealtime/Pade#129]
When the computer is booted (user login), Pade - Unified Communications at Work is launched twice, two program windows appear. (При загрузке компьютера (входе пользователя) Pade - Unified Communications at Work запускается два раза, появляется два окна программы)

**Comment by AGNaumov** [comment]
After booting the computer (user login), close one window of the two running. Next, click on the Pade - Unified Communications at Work application launch shortcut in the browser to open the second Pade - Unified Communications at Work window again. If, after booting the computer (user login), close both windows Pade - Unified Communications at Work and start from the launch shortcut in the browser, then the second window will not start again. (После загрузки компьютера (входе пользователя) закрываем одно окно из запущенных двух. Далее кликаем в браузере по ярлыку запуска приложения Pade - Unified Communications at Work опять откроется второе окно Pade - Unified Communications at Work. Если после загрузки компьютера (входе пользователя) закрыть оба окна Pade - Unified Communications at Work и запустить с ярлыка запуска в браузере то повторно второе окно не запускается)

**Comment by deleolajide** [comment]
**I am unable to reproduce this error.** 

My PC upgraded to version 1.0.7 this morning with no issues. I have rebooted PC and I only have a single Pade Converse Window.

First check your preferences/settings. The second window could be an application window like WhatsApp or Skype with auto-start enabled like this

![image](https://user-images.githubusercontent.com/110731/53791963-8d165600-3f22-11e9-88b4-5260bf669968.png)

That will case multiple Pade windows to appear on the Windows taskbar like this

![image](https://user-images.githubusercontent.com/110731/53792350-6573bd80-3f23-11e9-8c6c-28b56be355f0.png)

**If that is not the case, then I suggest you uninstall and re-install.**

**Comment by AGNaumov** [comment]
After rebooting the computer (После перезагрузки компьютера)
![image](https://user-images.githubusercontent.com/48155843/53794066-c4582780-3f61-11e9-8950-aad18c036d97.png)
![image](https://user-images.githubusercontent.com/48155843/53793991-9ffc4b00-3f61-11e9-9fc7-0ffc64879f24.png)
Maybe this is my glitch, tell me where to look? (Может быть это у меня какой то глюк, подскажите где можно посмотреть?)

**Comment by deleolajide** [comment]
Best thing is to start all over again. Uninstall Pade@Work, reboot PC and confirm it is removed and then go to the Chrome store and install it again. 

Make sure you don't have any Pade desktop shortcuts is Startup.

**Comment by AGNaumov** [comment]
Thanks for the advice, removal and reinstallation fixed the situation. (Спасибо за совет, удаление и повторная установка исправила ситуацию)

**Comment by AGNaumov** [comment]
Если Googl Chrome работает под одним пользователем на нескольких компьютерах и в google Chrome настроена синхронизация данных, Pade после перезагрузки компьютера запускается два раза.

Google translation by translator:

If Googl Chrome is running as a single user on multiple computers and data synchronization is configured in google Chrome, Pade runs twice after restarting the computer.

**Comment by deleolajide** [comment]
I am still unable to reproduce this issue. I always have google data synch on

![image](https://user-images.githubusercontent.com/110731/56082919-837fe800-5e16-11e9-9187-f4cd1ab735cd.png)

**Comment by AGNaumov** [comment]
Эта проблема появляется не каждую перезагрузку. Причина мне неизвестна, но условия при которых эта проблема появляется я смог выяснить. Google Chrome синхронизирует данные через один аккаунт на двух и более компьютерах. Pade также используется на этих компьютерах.

Google translation by translator:

This problem does not appear every reboot. The reason is unknown to me, but the conditions under which this problem appears I could find out. Google Chrome syncs data through one account on two or more computers. Pade is also used on these computers.

**Comment by deleolajide** [comment]
I suspect it is a chrome bug. Please re-open if it happens again
