### ISSUE TITLE
Message action buttons

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/Pade#133]
Add more action buttons on individual messages to the current single **edit** button in Converse. Provide the following actions to messages:

1. Pin a message and jump back to it from the info panel
2. Reply the first sentence in a message or the current selected text in the message. Copy and paste the text into the textarea for editing.
3. Share a message by copying to clipboard.
4. Implement **like** and **dislike** message reactions

**Comment by deleolajide** [comment]
Done. Now available in version 1.0.8

![image](https://user-images.githubusercontent.com/110731/54155087-5026f380-443b-11e9-8a01-9eb1e3ced8e2.png)

**Comment by marclaporte** [comment]
Congrats on these new features, especially like and dislike!
