### ISSUE TITLE
openfie remote desktop control

### ISSUE THREAD

**Issue by xujun738** [igniterealtime/Pade#140]
Now I have setup the Openfire Meetings and Bookmarks plugin on my openfire server and 
setup the chrome plugin Pade.Until now I can share my desktop to another one but can not 
control .What should i do to control others's computer like teamviwer. Thanks anyway.

**Comment by deleolajide** [comment]
Please look at existing issues before creating new ones. See https://github.com/igniterealtime/Pade/issues/24
