### ISSUE TITLE
Expose `muc_show_join_leave` checkbox in Converse settings

### ISSUE THREAD

**Issue by licaon-kter** [igniterealtime/Pade#144]

**Comment by deleolajide** [comment]
It is already exposed.  It is called group chat status messages

![image](https://user-images.githubusercontent.com/110731/55184617-84fcaf80-518a-11e9-9bc7-53b4070ca0bc.png)

**Comment by licaon-kter** [comment]
Thanks, the description doesn't seem to be related, hence me missing it.

**Comment by deleolajide** [comment]
> Thanks, the description doesn't seem to be related, hence me missing it.

Sorry. I had already named it before I found muc_show_join_leave :-)
