### ISSUE TITLE
Pade keeps re-setting my online status message to "hello"

### ISSUE THREAD

**Issue by luciash** [igniterealtime/Pade#145]
Even when I have explicitly set "I'm online" in the "Active Status" field, when I return from idle (away) to online status it changes to "hello". It does not happen on first launch of the Pade window. Only after going away and then returning back the status auto-changes...

**Comment by deleolajide** [comment]
It because you have auto-presence set on with a different default status message. I suggest you switch auto-presence off by dragging the slider to ZERO

![image](https://user-images.githubusercontent.com/110731/55231537-cdfc4480-521a-11e9-8d25-b37b1b06a543.png)

**Comment by luciash** [comment]
But it keeps setting "hello" even if I do not have filled anything in there in the "Active Message" field.

**Comment by deleolajide** [comment]
Ok. I get it now. If you have not filled in another message here, you want it to use the message you set in converse when it goes back to state "online" from "away".

**Comment by deleolajide** [comment]
Done. Now available in version 1.1.5
