### ISSUE TITLE
A typo in settings

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/Pade#146]
At https://github.com/igniterealtime/Pade/blob/f5ce066bbcd7f8a542f3b239a0667f12df13bb84/extension/options/manifest.js#L1135 it should say Always instead of Aways

**Comment by deleolajide** [comment]
Thanks and done. It will be available in next version 1.1.5

**Comment by deleolajide** [comment]
File format is not UTF-8. See https://github.com/igniterealtime/Pade/issues/149

**Comment by wrooot** [comment]
https://github.com/igniterealtime/Pade/pull/151
