### ISSUE TITLE
Cleanup media content which is no longer available from the Information > Media Content listing

### ISSUE THREAD

**Issue by luciash** [igniterealtime/Pade#148]
When you go to Converse > Information > Media Content listing it should not list content which is not available anymore on the server (it shows broken images and 0:00 video previews).

**Comment by deleolajide** [comment]
It is too expensive (CPU wise) for the media content plugin to pre-fetch and determine that every listed resource is no more available on the server. Also the item is listed for audit/reference purposes and not necessary to retrieve. 

As it is not removed from the chat history, why remove it from content summary?

**Comment by luciash** [comment]
OK, then I suggest to put a "This content is no more available" instead of trying to show a broken image or media.

**Comment by deleolajide** [comment]
Done. Now available in version 1.2.0

I forgot link fetching was done asynchronously. Links are now pre-fetched and validated before being displayed. No more broken images, videos, etc

Also, clicking on the link opens the link in the main browser window. If the link is still in the chat history, then the messages containing the link is scrolled into view just like pinned messages.
