### ISSUE TITLE
manifest.js is not in UTF

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/Pade#149]
When i have discovered a typo i wanted to fix it with PR, but when i try to edit https://github.com/wrooot/Pade/edit/master/extension/options/manifest.js in GitHub it says that encoding is ISO-8859-1 and says it will convert to UTF-8. I didn't want to break something, so didn't PR. haven't checked all the files, but most are ok, just this one.

**Comment by deleolajide** [comment]
They should be in UTF-8, but my text editor does weird stuff at times. Go ahead and edit. lest see what happens :-)

**Comment by wrooot** [comment]
You have already closed https://github.com/igniterealtime/Pade/issues/146 but the code is not changed yet. Can i PR?

**Comment by deleolajide** [comment]
I corrected the typo, but the file is still in ISO. I will reopen. I will revert my change and you can PR

**Comment by wrooot** [comment]
I wonder why i don't see your changes in the repo/commits and that file is unchanged for me.

**Comment by wrooot** [comment]
https://github.com/igniterealtime/Pade/pull/151
