### ISSUE TITLE
Option to show join/leave messages

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/Pade#153]
Converse.js shows them, so maybe you can add an option to enabled them? I like to be informed instantly when someone leaves or joins without having to keep an eye on the participants list.

**Comment by wrooot** [comment]
I have this enabled, but i don't see join or leave messages in group chat.

**Comment by deleolajide** [comment]
Are you looking for this?

![image](https://user-images.githubusercontent.com/110731/55436932-83b9f100-5595-11e9-96dd-498df9204b20.png)

You may have to close/reopen converse window for most options to take effect. Could it that?

**Comment by wrooot** [comment]
Yes, i want these messages. I had this setting on from the beginning, so i have closed Pade many times since last week. Maybe i should uncheck and check it again.

**Comment by wrooot** [comment]
I have tried deselecting that setting, restarting Chrome and Pade, then selected again, restarted again. Still don't see messages when someone joins or leaves group chat. Maybe this is again some nuance with Windows 7, though this works in Converse.js embedded chat.

**Comment by deleolajide** [comment]
The only thing I can suggest is to do a factory reset. See bottom of preferences screen.

![image](https://user-images.githubusercontent.com/110731/55507054-cab7ed00-564e-11e9-9071-ce115c8b94dd.png)

**Comment by wrooot** [comment]
This didn't help. Btw, why do you have 1.1.6? Mine is 1.1.5 :)

**Comment by deleolajide** [comment]
> This didn't help. Btw, why do you have 1.1.6? Mine is 1.1.5 :)

After every release, I immediately go up a version for the next cycle of dev->test->release :-)

The other thing you can do is to press F12 to open the chrome dev tools window and see if there any errors in the log. Right click and use save as to create a log file. Send that to me privately at discourse.igniterealtime.org if you can to look at.

**Comment by wrooot** [comment]
Sent

**Comment by deleolajide** [comment]
It was invisible due to a CSS issue in the default **fly-concord** style . If you selected a different style like **plain simple**, it will be seen.  It is now fixed and available in version 1.1.6
