### ISSUE TITLE
Window size and position preserved only until Chrome is closed

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/Pade#155]
I have set to save Windows positions and size in Pade@Work. If i close just Pade and reopen it, it remembers the size and position. If i exit Chrome process and start it again, then Pade opens with the default size.

**Comment by deleolajide** [comment]
It is a known issue. When a chrome extension window is opened in minimized state, Chrome ignores the provided window size and position values. 

I can add a new preference to choose to use minimized or normal state at startup.

**Comment by wrooot** [comment]
Yes, i can try that. It is even better if it starts not minimized, as I don't have to click again to bring it up.

**Comment by deleolajide** [comment]
Done. Now available in version 1.2.0

![image](https://user-images.githubusercontent.com/110731/55666555-97d94900-5848-11e9-988c-e708315b46d4.png)
