### ISSUE TITLE
notification numbering/dots on group chats

### ISSUE THREAD

**Issue by markra55** [igniterealtime/Pade#167]
Hello,

Could you add notification numbering/dots on the group chats so that it's easy to see which group has an update?

This would be useful for contacts that are grouped as currently, I need to expand each group to find who has messaged me directly. if it was at a group level I can easily expand on the group.

Mark

![image](https://user-images.githubusercontent.com/49949301/56743434-76e08580-676e-11e9-880d-afe90c8382a3.png)

**Comment by deleolajide** [comment]
This is a very good suggestion and feature request, but I am unable to implement it in Pade. It is best implemented upstream in Converse.js directly. I would be surprised if there is not already an issue raised for this.

As a work-around, disable groups and use a  single contact list. Online contacts bubble to the top of the list to give a btter chance of seeing unread messages or use the active conversations view 

![image](https://user-images.githubusercontent.com/110731/56826408-79210d80-685c-11e9-8ce3-f81f5a1cc10d.png)

**Comment by markra55** [comment]
Hello Deleolajide,

Many thanks for being so responsive!  I will take a look and see if this has already been raised in  Converse.js  (fingers crossed)   I found I can click on the 3 horizontal lines (Americans call it the burger)  and I can see who's notified me there.

Thanks again for a great app.

Cheers

Mark
