### ISSUE TITLE
logging into Pade

### ISSUE THREAD

**Issue by markra55** [igniterealtime/Pade#168]
Hello,

I have noticed that setting up Pade for the first time it attempts to log in to the server and never completes.   to work around this I have to access

https://server.example.com:7443/ofmeet log in using my [LDAP]  username & password and then the app works after this.

Cheers

Mark

**Comment by deleolajide** [comment]
You need to install certificates on your XMPP server (openfire). It does not work with self-certification.

Opening that url on a browser only gives temporary permission which will expire. This may work while testing, but not recommended for live use
