### ISSUE TITLE
Cannot use end-to-end encryption / client that doesn't support OMEMO.

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/Pade#169]
Hello,

When i try to enable encryption, we have the message "Cannot use end-to-end encryption / client that doesn't support OMEMO" . We are using Padé & or Xabber to connect, We use Padé 1.25 version. Possibly a regression as it was working on a previous release. 

![screenshot14](https://user-images.githubusercontent.com/29485972/56863919-cd430380-69bc-11e9-83e0-457fdc51023c.png)

**Comment by deleolajide** [comment]
OMEMO is not working with Pade right now. See https://github.com/conversejs/converse.js/issues/1524

**Comment by deleolajide** [comment]
Please retry in version 1.3 and re-open issue if it does not work.
