### ISSUE TITLE
Change my user password in Padé

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/Pade#171]
Hello,

Is there a way to change my user password via Padé ?

Thx in advance for inputs

**Comment by deleolajide** [comment]
Not at the moment. Thank you for the feature request. I try to add it.

**Comment by deleolajide** [comment]
Done. Now available in version 1.2.6

![image](https://user-images.githubusercontent.com/110731/57196162-03026200-6f52-11e9-8c2d-4a800bf23dd2.png)
