### ISSUE TITLE
When chrome is closed message corresponding to the notification are lost in Padé

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/Pade#173]
When chrome is closed, messages received via notification are lost in Padé thread
Probably on MS-WIN10 not seen on Linux
Close browser, receive a message sent via a contact on Padé, then go to Padé, message does not appear in Padé Chat
![screenshot8](https://user-images.githubusercontent.com/29485972/57163766-637a8d80-6df2-11e9-9dbe-ce7235c9c6b7.png)
![screenshot12](https://user-images.githubusercontent.com/29485972/57163921-c79d5180-6df2-11e9-8269-7d0fbc5f39a1.png)

**Comment by Pascal-KOTTE** [comment]
I am on a Chrome Version 73.0.3683.103 (Build officiel) (64 bits)
Windows 10 v1803 (17134.706)
![Capture plein écran 03 05 2019 220912 bmp](https://user-images.githubusercontent.com/7036634/57163850-96248600-6df2-11e9-891d-5165db87a5d2.jpg)
The notified message is not displayed in the chat history, all the same after refresh, or re-login, closed reopenend from the Chrome extension.

**Comment by Pascal-KOTTE** [comment]
In fact I must say I do not close the Chrome, only the Pade

**Comment by deleolajide** [comment]
Please make sure you are using openfire monitoring plugin version 1.7.x and archiving is enabled 

![image](https://user-images.githubusercontent.com/110731/57196223-b5d2c000-6f52-11e9-8d9a-bb8267b367fb.png)

**Comment by ClaudeStabile** [comment]
Dele,

you can close this one same as message offline issue. It is fix with monitoring plugin update to 1.7.2 confirmed :)
