### ISSUE TITLE
Changelog containts same ticket twice

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/Pade#174]
<p><b>1.2.6</b> -- <i>April 28, 2019</i></p>
<ul>
    <li><a href="https://github.com/igniterealtime/Pade/issues/166"><b>Fixed #166: Support RSS & Atom feeds</b></a></li>
</ul>

<p><b>1.2.5</b> -- <i>April 25, 2019</i></p>
<ul>
    <li><a href="https://github.com/igniterealtime/Pade/issues/165">Fixed #165: Xmpp account creation</a></li>
    <li><a href="https://github.com/igniterealtime/Pade/issues/166"><b>Fixing #166: Support RSS & Atom feeds</b></a></li>
</ul>

**Comment by deleolajide** [comment]
I use **fixing** and **fixed** when an existing ticket is re-opened and I have to re-fix or fix something new or a side effect issue.
