### ISSUE TITLE
Missing offline messages

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/Pade#179]
If i receive a message while i'm offline and then i run Chrome and Pade automatically starts with it, i see a popup about the new message with buttons View and Ignore. But pressing View opens chat window with that person and new message is not shown. It is also not shown when reopening the window. So Pade catches such offline message, but for some reason discards it without saving to history.

**Comment by deleolajide** [comment]
Pade uses a background xmpp connection in addition to the Converse xmpp connection. When the Converse window is closed, all messages go to the background connection. This creates the message notification popup, but the message will only be seen in when the Converse window is opened via MAM chat history. If the monitoring plugin is not enabled, the message will not show in the chat history as Pade sets Converse to **always** use MAM.

A work-around might be to set Openfire property **route.all-resources** to TRUE to make sure both connections receive the offline messages. I have not tested this and unable to confirm.

If that does not work, then I may have to add a preference setting to enable/disable MAM in order for offline messages to be handled on Converse. I need to check code to confirm that as well.

**Comment by wrooot** [comment]
FYI, this is happening on igniterealtime.org server.

**Comment by deleolajide** [comment]
I don't think igniterealtime.org server  is running monitoring plugin with MAM v2 required by Converse

**Comment by ClaudeStabile** [comment]
Dele,

I have same issue on Free-Solutions servers. I have the monitoring plugin but with or without pb is being observed. Let me know if i should try out with parameter route.all-resources to TRUE

**Comment by deleolajide** [comment]
> I have the monitoring plugin

What version?

**Comment by ClaudeStabile** [comment]
Padé version 1.2.7 + monitoring 1.70 set, still the problem offline messages are gone
I receive messages via xabber android client, does not loose any offline mess
![screenshot8](https://user-images.githubusercontent.com/29485972/58321317-1ea8ac00-7e1e-11e9-80d5-69ffc93bc412.png)
![screenshot8](https://user-images.githubusercontent.com/29485972/58321345-31bb7c00-7e1e-11e9-9df1-8d8a82388284.png)

btw my parameter route.all-resources is already set to TRUE by default

**Comment by deleolajide** [comment]
1.7.0 does not handle MAM properly. 
Try this one
![image](https://user-images.githubusercontent.com/110731/58340877-cdf87980-7e44-11e9-8988-182c1692ae70.png)

Download from https://github.com/igniterealtime/Pade/releases

**Comment by ClaudeStabile** [comment]
Hi Dele,
Just to confirm it fixes the problem at Free-Solutions too. Now ofline messages are in Padé You can close related issues i open for this.

Thanks :)

**Comment by wrooot** [comment]
If 1.7.1-SNAPSHOT fixes MAM, maybe we should release it?

**Comment by deleolajide** [comment]
It is more of a hack than a proper fix. It advertises MAM2 for service discovery and relies on Converse to create the missing stanza-id. @guusdk wants to fix the monitoring plugin issues as soon as he can afford the time.
