### ISSUE TITLE
Make the application work as a web page and as a progressive web app

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/Pade#180]
Pàdé runs installs as a browser extension and runs like a desktop application. In some use cases where browser extensions are not permitted, it is desirable to run Pàdé as basic web page or install and run as a progressive web app. This is most desired for mobile devices

**Comment by deleolajide** [comment]
In order to support a web page or progressive web app (PWA), a web server with web push support is required. This feature will require the Openfire Chat API plugin to host the Pàdé web application. Perform the following changes to Pàdé:

1. Enable Pàdé to work work as a PWA that installs like a native app on the desktop or mobile. 

2. Support web push directly from Openfire using VAPID and a service worker to open Pàdé when messages are received and the user is offline.

3. Support single sign on with browser stored username/password using the Credential Management API. User should experience the Converse login or registration screen only once. 

4. Adjust the already responsive Converse UI  for a mobile form factor

5. Handle PWA caching

**Comment by deleolajide** [comment]
Done. Changes implemented in version 1.2.8 and available in public web site 
http://pade.chat
Register a new account and test it.

To deploy locally, you would need Openfire Chat API plugin version 0.9.5 Release 3

Installs on the  mobile phone home screen

![image](https://user-images.githubusercontent.com/110731/58328264-97f9cc00-7e29-11e9-8475-a36bd1f9be52.png)

Converse responsive UI

![image](https://user-images.githubusercontent.com/110731/58328570-50c00b00-7e2a-11e9-9c75-027cef071dbd.png)

![image](https://user-images.githubusercontent.com/110731/58328583-56b5ec00-7e2a-11e9-8241-7fe5da5e41a0.png)

Installs on the desktop 

![image](https://user-images.githubusercontent.com/110731/58328434-fb83f980-7e29-11e9-8385-d558d79173d2.png)

![image](https://user-images.githubusercontent.com/110731/58329270-18b9c780-7e2c-11e9-9d07-e2e8eef3eb76.png)

Single sign-on with Credential Management API. 

![image](https://user-images.githubusercontent.com/110731/58329184-db553a00-7e2b-11e9-9427-26a5301bdb91.png)

Web Push

![image](https://user-images.githubusercontent.com/110731/58328929-481c0480-7e2b-11e9-9cf7-2398454ec016.png)

**Comment by wrooot** [comment]
This http://pade.chat accepts only new accounts? Wasn't able to login with my igniterealtime account.

**Comment by deleolajide** [comment]
> This http://pade.chat accepts only new accounts?

Yes. The domain is pade.chat.

**Comment by marclaporte** [comment]
wow.

Just wow!
