### ISSUE TITLE
Branding parameters are not applied to main web page in PWA mode

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/Pade#181]
Hi,

I have noticed in PWA web mode that parameters defined in branding.js only apply to options.html page.
So if you need branding parameter to be set you need to navigate to /apps/options then back to /apps and options are set. Would be nice to have branding parameter applied at first connect to /apps

Thx :)

**Comment by deleolajide** [comment]
Fixed. Will be available in openfire-chat-api plugin version 0.9.5 Rel 4
