### ISSUE TITLE
PWA mode / geolocalisation is not working PC and Mobile phone

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/Pade#182]
When location is shared, geolocation is not available for contacts. Would be great to have geolocalisation in PWA mode for mobiles. Same problem when using a computer in PWA mode.

**Comment by deleolajide** [comment]
Fixed. Will be available in openfire-chat-api version 0.9.5 Rel 4

**Comment by deleolajide** [comment]
Yes indeed. Unfortunately, it depends on the browser extension background XMPP connection that Pade uses which is not available in PWA mode. The plan is to move some of these background tasks to a Converse plugin instead. However, it the user closes their Converse window, they will stop broadcasting their presence.

**Comment by deleolajide** [comment]
Fixed. This will be available in openfire-chat-api plugin version 0.9.5 release 4

![image](https://user-images.githubusercontent.com/110731/58491335-b3850f80-8166-11e9-883c-31a80723dde8.png)

**Comment by ClaudeStabile** [comment]
Cool :)
