### ISSUE TITLE
Account creation failed in PWA mode if Email and display name is entered

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/Pade#185]
When i create new accounts it succeed if i do not enter Email & display name but failed otherwise.

To reproduce : navigate to https://www.free-solutions.org/apps register for a new account try with and without email and display name

![notcreatedaccount](https://user-images.githubusercontent.com/29485972/58761966-6b8d3080-854a-11e9-9e43-ab5a5e04a36a.png)

**Comment by deleolajide** [comment]
I can't reproduce this issue. I will try again. Next time you have it, try to refresh the web page

**Comment by ClaudeStabile** [comment]
Hi dele,

It is very strange, sometimes it goes sommetimes not. I ll trap the console next time i have the issue.
I ve try 2 times it works it seem to happen not at every attempt.
Most of the time i got it on android, probably cache effect.
Close this one :)
