### ISSUE TITLE
Orientation on android tablet or phone set to portrait, after opening options.html set up page

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/Pade#186]
Hello,

We have the following behavior on android 

When we go through options (gear at the top) on android in PWA mode, orientation is set definitively to portrait, no way to use landscape after option page has been open.

And option to set & choose lock (portrait - landscape") would be a great + for Padé

Thanks a lot in advance for all efforts made on this wonderful project

**Comment by deleolajide** [comment]
You can change this by editing the PWA manifest file called manifest.json  at OPENFIRE_HOME/plugins/ofchat/classes/apps/manifest.json

```
{
    "short_name": "pade.chat",
    "name": "pade.chat",
    "description": "Unified Communications web client",    
    "icons": [
        {
            "src": "images/image_192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "images/image_512.png",
            "sizes": "512x512",
            "type": "image/png"
        }
    ],
    "start_url": "./",
    "background_color": "#FFFFFF",
    "theme_color": "#FFFFFF",
    "display": "standalone",
    "orientation": "portrait"
}
```

Change the value of orientation. See for more details see
https://developers.google.com/web/fundamentals/web-app-manifest/
https://developer.mozilla.org/en-US/docs/Web/Manifest
