### ISSUE TITLE
Duplicate messages on some servers

### ISSUE THREAD

**Issue by marclaporte** [igniterealtime/Pade#190]
![2019-06-26_111030](https://user-images.githubusercontent.com/1004261/60191964-2c799480-9803-11e9-9b66-495dc2161a73.png)

**Comment by deleolajide** [comment]
It is a known issue and will probably remain unfixed until next version of converse. For now, may I suggest that you do a clear and refresh (thrash and recycle icons on toolbar). That will remove the duplicates.

**Comment by marclaporte** [comment]
ok, I see it's fixed upstream: https://github.com/conversejs/converse.js/pull/1436

Thanks!

**Comment by marclaporte** [comment]
ah, wait, no.

#1414 Prevent duplicate messages on MUC join is reported fixed in 4.1.1:
https://github.com/conversejs/converse.js/blob/master/CHANGES.md#411-2019-02-18

**Comment by deleolajide** [comment]
This should be fixed in version 1.3. Please check and reopen if not.
