### ISSUE TITLE
Notifications on Android / Only some messages are notified PWA vers 1.2.11

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/Pade#194]
Dear coders,

On android, Only some chat messages are notified, link is now open to proper conversation when it comes. When notified only first message is received.

Thanks in advance for efforts & corrections

**Comment by ClaudeStabile** [comment]
Most of sent messages are not notified on Android R5,
Probably related to change https://github.com/igniterealtime/Openfire-Chat/issues/12
Back to R4, i got expected behaviour, 

Hope this helps :)

**Comment by deleolajide** [comment]
This is fixed in R6 of the Openfire Chat API plugin as default behavior. Notifications are always sent until user activates the web app and presence changes to available.

To changes to push only first notification, set openfire property **plugin.ofchat.push.always** to false.
