### ISSUE TITLE
Prompt to keep copy of messages when leaving a room or chat

### ISSUE THREAD

**Issue by rodrigolzd** [igniterealtime/Pade#195]
Hello. 

When leaving a room, Pade could ask if the user wants to keep a copy of the messages.

for example, if I join a room where I'm asking for support but don’t intent to keep it bookmarked, it would be nice to somehow get a copy of the chat, perhaps created to a txt file I could save or some other way to keep it
This would be different from copying selected messages

How do you determine where to start and where to stop for the scope of the chat conversation?

One idea would be options: All, 1 day, 2 days, and 1 week

Say I join a room right now, I don’t think it will load messages for a month just for joining, I assume it would probably start from that point on, up to where I leave the room.
I guess it would be something similar to support chat logs like in Fastpath and alike

It could be a feature that is turned off by default or the prompt to save every time I exit a room could be a pain if the user does not want to save chat history.
I would put it in the info panel and provide a pulldown list to select scope

Perhaps have a function key to enable it.

**Comment by deleolajide** [comment]
I am going to use the chat history PDF generation feature of the monitoring plugin to implement this. The plan is to use calendar.js as the UI to select the scope of the chat history.

**Comment by deleolajide** [comment]
Done. This is now available in Pade version 1.3.2. It requires the chat api plugin for openfire.

![image](https://user-images.githubusercontent.com/110731/64371578-cbe3b080-d018-11e9-9a66-4edb0cbc013c.png)
