### ISSUE TITLE
Pade version 2.x

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/pade#196]
Pàdé started life as a chrome extension for webrtc screen sharing when using Jitsi Meet. It later got extended with CTX SIP phone and Converse.Js to become a full unified communications client. More recently, it was modified to run as a web page or a progressive web page in addition to the default chrome extension mode.

It is time to refactor the code to remove unused and redundant legacy code, support other browsers like Firefox, use a single xmpp connection for the browser extension foreground and background processes.

**Comment by deleolajide** [comment]
At the moment, Pade uses a lot of permissions.

![image](https://user-images.githubusercontent.com/110731/61870184-6955ab80-aed5-11e9-9f18-26f35d9aaf20.png)

The plan is to reduce it to

![image](https://user-images.githubusercontent.com/110731/61870287-9f932b00-aed5-11e9-8b4e-28de70cecd06.png)

in order to remain within the safe threshold of submitting extensions to the web store.

Consequently, all the collaboration features of Pade that used *injected* content scripts are to be disabled in the default branding file. Anyone who requires these features should build their own extension and enable them.

**Comment by deleolajide** [comment]
CTX Phone (SIP) is to be removed. All SIP (Telephony) is be done server-side with the Jitsi Jigasi plugin for Openfire. Anyone who still requires legacy telephone type communications should stay with version 1.2.x or build their own custom extension.

**Comment by deleolajide** [comment]
CTX Phone is now replaced with the audioconf plugin. 
See https://github.com/conversejs/community-plugins/tree/master/audioconf

**Comment by deleolajide** [comment]
Version 2.0 is out for preview as pade@ignite. See https://chrome.google.com/webstore/detail/pade-at-ignite-realtime/iggkimchcpfjkphmammipgijendiompm

**Comment by wrooot** [comment]
As usually, a friendly reminder, that on Projects page it is still 1.2.6 ;)

**Comment by deleolajide** [comment]
This sub-project has been abandoned. The source code still exists for reference. All efforts will be concentrated on making Pade work as a web app/pwa on all browsers including FireFox.

Pade is now available as a browser extension in the Microsoft Addon store for Microsoft Edge. There are no immediate plans to maintain a seperate development for Firefox.
