### ISSUE TITLE
Losing messages

### ISSUE THREAD

**Issue by robertokir** [igniterealtime/Pade#198]
In Pade 1.3.1 with Converse 5.0.1 I'm losing messages (PMs). Factory reset doesn't solve this. In other XMPP clients the messages are still available.

**Comment by deleolajide** [comment]
Thanks for posting this issue :-)

Could you please paste an image of your conversation the next time it happens in order for me to confirm (from the time-stamps) if the messages are missing from the chat history stored in the Openfire monitoring plugin DB.

I am currently debugging a similar issue,  but in my case the messages were never saved in the DB.

**Comment by marclaporte** [comment]
What I see:   I chat and all seems good. I click refresh, and most recent messages do not re-appear.

**Comment by marclaporte** [comment]
![Video_2019-08-31_145444](https://user-images.githubusercontent.com/1004261/64067979-8598e680-cbff-11e9-9378-bfbf6a9caab9.gif)

**Comment by robertokir** [comment]
![Screenshot Editor (3)](https://user-images.githubusercontent.com/33861038/64166038-2b399900-ce3e-11e9-9722-85d97464dfd5.png)

Timeago doesn't help identifying when this happened. But it was yesterday (Monday) morning, say about 10h? Where the arrow appears, there should be a message from me announcing the release of tiki 20.1 and recruiting volunteer testers, to which Rodrigo Lozada replied.

**Comment by deleolajide** [comment]
> What I see: I chat and all seems good. I click refresh, and most recent messages do not re-appear.

We still have an outstanding one2one chat history issue with openfire. MAM2 support is only provided for MUC. See @guusdk comment in https://github.com/igniterealtime/openfire-monitoring-plugin/issues/5

**Comment by deleolajide** [comment]
> Timeago doesn't help identifying when this happened. But it was yesterday (Monday) morning, say about 10h? Where the arrow appears

Thanks. This helps a lot :-)

**Comment by deleolajide** [comment]
![image](https://user-images.githubusercontent.com/110731/64169080-d77e7e00-ce44-11e9-8805-5290ac60ecdb.png)

Looks like the message never got saved. As Rodrigo responded, I can only assume the message go to the server. Looks like it is an issue with monitoring plugin. I think I will create an issue there and reference this for the attention of @guusdk

**Comment by guusdk** [comment]
Is there any kind of error in the logs around that time? I've previously seen a database error preventing a message from being stored in the archive.

**Comment by deleolajide** [comment]
I suspect this error was connected to the offline messaging issue on the server. I will reopen if it re-occurs
