### ISSUE TITLE
Disconnect and reconnect loop

### ISSUE THREAD

**Issue by ThunderITA** [igniterealtime/Pade#199]
Hi,

in pade 5.0.1 on openfire 4.4.1 the application every 2/3 mins closed connection and reconnect. With spark 2.8.3 work fine.

Tks

**Comment by deleolajide** [comment]
Can you please do a factory reset and re-enter your password. If you still have an issue, then try to disable web-sockets.  If you still have an issue, the open chrome dev console (F12), download the console log and post it to me privately.

**Comment by ThunderITA** [comment]
libsignal-protocol.js:136 pre-main prep time: 2 ms
index.js:234 doConverse 192.168.3.200:7443 ma***.del*** false
index.js:473 converse.initialize Object
gateway.js:69 gateway plugin is ready
info.js:89 info plugin is ready
payments.js:139 payments plugin is ready
markdown.js:50 markdown plugin is ready
search.js:140 search plugin is ready
directory.js:131 directory plugin is ready
invite.js:107 invite plugin is ready
vmsg.js:75 vmsg plugin is ready
webmeet.js:638 webmeet plugin is ready
converse.js:63327  ERROR: Error while fetching bookmarks
./src/headless/converse-core.js._converse.log @ converse.js:63327
pade.js:402 pade plugin is ready
converse.js:63327  ERROR: <iq xmlns="jabber:client" type="error" id="4b7d67db-08ea-46d4-9030-39395019cf94:sendIQ" to=*********@openfire.workgroup/pade@work-converse-v5.0.1-Chrome76Win10.64-118617362" from="rss@pade.DOMINIO.it"><pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="eu.siacs.conversations.axolotl.devicelist"/></pubsub><error code="404" type="cancel"><remote-server-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>
./src/headless/converse-core.js._converse.log @ converse.js:63327

**Comment by deleolajide** [comment]
I don't think https://192.168.3.200:7443 is going to work as your server. Do you have a certificate for 192.168.3.200? Try https://dominio.it:7443

**Comment by deleolajide** [comment]
Unable to reproduce this issue. I suspect it is certificate problem
