### ISSUE TITLE
Lag time entering message

### ISSUE THREAD

**Issue by haroldkyle** [igniterealtime/Pade#209]
When I type a message in the "Type message" field, there is a significant delay before the text shows up in the textarea. The lag can be longer than 10 seconds. Sometimes the text doesn't appear at all without a click event in the textarea. I'm using v5.0.5 on a PC. This issue wasn't happening prior to this version.

**Comment by haroldkyle** [comment]
This problem might happen when there are many contacts shown in the conversations view on the left. I had about 15 open when this happened. Once I narrowed this down to 2 open conversations, the problem stopped.

**Comment by deleolajide** [comment]
I have seen it happen when I enabled time-ago on messages. I will keep a lookout for it again. When it happens again, please open the browser console inspector window (F12 or CTRL-SHIFT-I) and take a screenshot of any JavaScript errors.

**Comment by deleolajide** [comment]
I think I found the reason. A recent change to intercept typing in order to automatically switch focus to textarea on the first keystroke is badly implemented by me. Removing it for now.

**Comment by haroldkyle** [comment]
When this happened last week, I disabled time-ago but didn't see immediate improvement. I also inspected for JS errors while this happened but there was nothing of note in the console. This week things are running smoothly...perhaps because I'm closing conversation windows more quickly.

**Comment by deleolajide** [comment]
Thanks for feedback. In any case, I have removed the focus switching code in version 1.5.6 which is waiting for approval in chrome store.

**Comment by deleolajide** [comment]
Fixed in version 1.5.6
