### ISSUE TITLE
Support the Stream Deck device as a TouchPad

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/Pade#21]
Add support for the Elgato Stream Deck device using the [OpenStream API](https://github.com/OpenStreamDeck/StreamDeckSharp) and chrome native messaging

**Comment by deleolajide** [comment]
Done. I quite like it 👍 

![stream_deck2](https://user-images.githubusercontent.com/110731/40426733-b9c7fc6e-5e93-11e8-9e3e-d982da183482.jpg)

**Comment by guusdk** [comment]
And such a handsome fellow in the bottom-left corner! ;)
