### ISSUE TITLE
Add option to display full names (nicks) instead of usernames in the user roster

### ISSUE THREAD

**Issue by luciash** [igniterealtime/pade#210]
![image](https://user-images.githubusercontent.com/4555037/74761390-3eb9ae80-527c-11ea-9aae-96f6278986b3.png)

**Comment by deleolajide** [comment]
Unfortunately, this is a server side issue with Openfire and the user directory. There are no user full names on the serevr

![image](https://user-images.githubusercontent.com/110731/74764992-abcc4480-527a-11ea-89c2-5abd6cdfbc8e.png)

**Comment by luciash** [comment]
@deleolajide :-(

> Unfortunately, this is a server side issue with Openfire and the user directory. There are no user full names on the serevr
