### ISSUE TITLE
How can we mass deploy settings remotely?

### ISSUE THREAD

**Issue by bmccorkle** [igniterealtime/pade#214]
I have group policy deploying Pade but I can't find a way to have it start up with some settings pre configured (server name, etc) so that users don't have to type this in (using single signon as well).  Is there a way to do this?

**Comment by bmccorkle** [comment]
Found some additional documentation and think I understand what needs to happen now.

**Comment by deleolajide** [comment]
Just to be sure. I am assuming you have found  https://github.com/igniterealtime/pade/issues/66

**Comment by bmccorkle** [comment]
Yes, thank you
