### ISSUE TITLE
JSXC as and alternative to Converse.js

### ISSUE THREAD

**Issue by sirinath** [igniterealtime/pade#215]
Is it possible to add [JSXC](https://www.jsxc.org/) as an alternative to Converse.js

**Comment by deleolajide** [comment]
It is possible, but I was not planning to do so. Could you kindly give me at least 3 reasons why I should invest time and effort into JSXC?

**Comment by sirinath** [comment]
I cannot give 3 but this seems like to have more standards implemented.

![image](https://user-images.githubusercontent.com/637415/76756827-7b5dc480-67ac-11ea-925f-b1b751c68e2b.png)

vs

![image](https://user-images.githubusercontent.com/637415/76756871-92041b80-67ac-11ea-8773-bc5d3693746a.png)

**Comment by deleolajide** [comment]
Nice, but I don't see anything there that is also not in ConverseJS
