### ISSUE TITLE
Sending Videos: Once sent, you will not get the video display, you will only get the audio

### ISSUE THREAD

**Issue by Kafindo** [igniterealtime/pade#223]
![info](https://user-images.githubusercontent.com/43158371/80790753-596fa400-8b98-11ea-830e-82b9d07527e1.jpeg)

**Comment by deleolajide** [comment]
Thank you for reporting this.  https://deleolajide.github.io/pade/ has now been upgraded from 1.6.2 to 1.6.8.
Please test again whenever you can and reopen if it is still an issue
