### ISSUE TITLE
PWA app install on Android & Win10, does not suggest to install app

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/pade#224]
On android and Win10, Pade app is not suggested to be installed on latest version. It was working perfectly on ofchat 0.9.5
Thanks in advance if you can fix this :)

**Comment by deleolajide** [comment]
Is it this you are looking for

![image](https://user-images.githubusercontent.com/110731/83396992-cc1cab00-a3f4-11ea-98ae-109526afdafa.png)

It should be fixed in version 1.6.4 of Pade to be released soon

**Comment by ClaudeStabile** [comment]
Yes, installable app on android and win10, is a very appreciated feature. Perfect that's Coool...and a very good news
Thanks a lot @deleolajide for all efforts done
++

**Comment by ClaudeStabile** [comment]
Dele,

Issue is fixed
You can close this issue, PWA install works fine on all devices android, mac, PC with Pade 1.6.6 :)
