### ISSUE TITLE
Message notification on Android and Linux chrome

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/pade#225]
Hi Dele :)

I still have problems with android notifications with latest Pade 6.0.0. Probably also with chrome/Linux i do not receive messages notifications as well. Hereafter current plugins i am using.
You can try out at https://vidchat.free-solutions.org

![screenshot26](https://user-images.githubusercontent.com/29485972/81088627-80f9a000-8efb-11ea-96b2-347922ce2721.png)
Padé version 
![screenshot27](https://user-images.githubusercontent.com/29485972/81088970-01b89c00-8efc-11ea-90e9-2cdd899a9ed8.png)

Thanks a lot in advance for efforts and progresses done

++

**Comment by deleolajide** [comment]
Web push notifications is still broken. I will look at it soon.
