### ISSUE TITLE
Meetings: Start with Video Muted doesnt work

### ISSUE THREAD

**Issue by tdrEEB** [igniterealtime/pade#229]
Hi,

"Start with Video Muted" does not work. It worked on the first 2 Meetings i started. After that it didnt.

I exported the settings file, modified it to ensure that its enabled and imported it again. Still no functionality.

Any ideas how to solve this?

**Comment by deleolajide** [comment]
It is a bug. 
https://github.com/igniterealtime/pade/blob/2659854bf5b61a7ef654208df239975f4da81d70/docs/js/background.js#L1186

Thanks for finding it. I will fix and post a new version shortly
