### ISSUE TITLE
User Directory in Padé Chat does not work

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/pade#236]
Hello,

We have found the folowing problem 
User directory icon in Padé Chat is not working Version 1.0.0

![screenshot46](https://user-images.githubusercontent.com/29485972/94676511-bd4ef200-031b-11eb-8d5e-5c517107e86e.png)
![screenshot45](https://user-images.githubusercontent.com/29485972/94676445-a01a2380-031b-11eb-8079-72af76a113b3.png)

Nothing happen when clicking on icon

**Comment by deleolajide** [comment]
Fixed in version 1.6.10
