### ISSUE TITLE
Add remote desktop control using the Java Robot class and Chrome Native messaging

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/pade#24]
Replicate a better version of ofmeet remote control (ver 0.3.x) . This time use the Java Robot class to control a remote mouse and keyboard instead of nodejs and take advantage of the together.js code already in Pade that does co-browsing and multiple user cursors

**Comment by deleolajide** [comment]
Decided to re-use the Jitsi-meet remote control UI and intercept the remote control commands being sent down the webrtc data channel. That part is working. Making those commnads work with Java Robot Class is next.

First enable remote control in Pade

![remote_control_0](https://user-images.githubusercontent.com/110731/40491864-18990318-5f67-11e8-8bd4-d6ed7e66ac52.png)

That will cause the remote control feature to appear for that user in a meeting

![remote_control_1](https://user-images.githubusercontent.com/110731/40491640-7fae9bf4-5f66-11e8-996c-508f6521006e.png)

Click on the icon to request permission to remote control. That will cause a prompt to appear in the UI of the user whose desktop can be controlled.

![remote_control_2](https://user-images.githubusercontent.com/110731/40491952-560f691c-5f67-11e8-9f4c-c4f9e4003a70.png)

That user can then allow or cancel.

![remote_control_3](https://user-images.githubusercontent.com/110731/40492079-9d2b8420-5f67-11e8-9b0e-ba702b447f29.png)

Allow will trigger the webrtc screenshare for only screens. No support for applications yet. Choose a screen if you have multiple monitors and that should starts the process.

![remote_control_4](https://user-images.githubusercontent.com/110731/40492309-1c2d29d6-5f68-11e8-9652-7842b556c6eb.png)

**Comment by deleolajide** [comment]
Now fully working in version 0.4.6. Needs documentation on how to setup before I can close Issue

**Comment by marclaporte** [comment]
My team can handle user documentation. Just need a working example, and we'll make nice screenshots and some explanations.

We document here?
https://igniterealtime.github.io/Pade/

Thanks!

**Comment by deleolajide** [comment]
Yes, the actual location in GitHub is

https://github.com/igniterealtime/Pade/tree/master/docs

Just submit PRs to add more documentation. It is vanilla HTML

-dele

Sent from Mail for Windows 10

**Comment by deleolajide** [comment]
There is also an oustanding task of packaging the Pade [Java native messaging client](https://github.com/igniterealtime/Pade/tree/master/remotecontrol) that actually controls the mouse/keyboard via the native messages from the Pade chrome extension. The packaging has to install correctly for OSX, Linux and Windows.

I will probably start with Windows first and would require assistance with OSX and Linux

**Comment by deleolajide** [comment]
Pàdé setup/installer/packager ver 0.1 for Windows now done and uploaded.

See https://github.com/igniterealtime/Pade/releases/tag/v0.1

**Comment by deleolajide** [comment]
Please note that only screen 1 can be remote controlled for now. I am seeking a solution that will support multi-screen desktops with the Java Robot Class

**Comment by premanandmanimaran** [comment]
Hello

I am trying create Skype for Business Alternative for my business. I looking to built Unified Communication Platform where my users login and have following features
1. Audio / Video Calling ( Option to auto accept)
2. Request Desktop Access ( Option to auto accept)
3. Co-Browsing 
4. SIP Calling
5. Conference
6. Text Chatting
7. Call Recording

Can you let me know if anybody can help us do this.

Prem

**Comment by marclaporte** [comment]
2 Windows computers with
* Both Pàdé 0.6.0
* Both installed Pàdé Remote Control (Windows) v 0.1
* Different XMPP accounts under same XMPP domain, with Openfire 4.2.3
I launched an audio/video call. Seems all normal. But I don't see the "icon to request permission to remote control" which "will cause a prompt to appear in the UI of the user whose desktop can be controlled"
![2018-10-19_174854](https://user-images.githubusercontent.com/1004261/47245900-21937800-d3c9-11e8-9e26-6c232e2f74bd.png)

**Comment by marclaporte** [comment]
@premanandmanimaran Those are all things that are done at various levels of quality. Join the community to make them even better!

Please see: http://wikisuite.org/Why-Openfire

**Comment by deleolajide** [comment]
First configure on PC that has installed the remote control native application

![image](https://user-images.githubusercontent.com/110731/47260650-6eee1300-d4b7-11e8-94d3-582b410ce020.png)

To debug, open the dev tools window for the chrome background page. Check log to see that extension is talking to binary app

![image](https://user-images.githubusercontent.com/110731/47260661-bb395300-d4b7-11e8-84cf-ca5ab6819892.png)

Start Jitsi Meet and check for remote control

![image](https://user-images.githubusercontent.com/110731/47260656-904eff00-d4b7-11e8-9062-f1f9f0bf0710.png)

**Comment by marclaporte** [comment]
I confirm we had both activated the "Enable Remote Control" checkbox.

I will ask 2 devs to try again and share their findings.

Thanks!

**Comment by deleolajide** [comment]
Use only Pade@Work. Pade@Home is not yet on the white-list of the remote control desktop application.

**Comment by marclaporte** [comment]
ahhh, that must be it!

**Comment by Skaylat** [comment]
Hello, the remote desktop option isn't showing between 2 participants

Openfire v4.5.2
Audio and video call working

Both Remote desktop : v0.2 and activate the "Enable remote control"
1- Opera Pade@Work v1.6.8 :
_generated_background_page : remote control incoming {message: "hello too"}

 2- Chrome Pade@Home v1.5.4 : 
_generated_background_page : "Access to the specified native messaging host is forbidden."
The extension id is the same as in the pade.remote.control.json file however

![image](https://user-images.githubusercontent.com/49161638/90336544-89598080-dfaa-11ea-9c3b-f82e4aab532f.png)

**Comment by deleolajide** [comment]
This is currently broken and not working

**Comment by Skaylat** [comment]
Hello, thanks for your fast answer
Do you have an ETA for this issue ?

**Comment by deleolajide** [comment]
> Hello, thanks for your fast answer
> Do you have an ETA for this issue ?

It was broken by [this issue](https://github.com/igniterealtime/pade/issues/220)
Jitsi-Meet is no more included in the chrome extension. This means that remote control has to be implemented directly in ofmeet.

No, I dont have an ETA

**Comment by deleolajide** [comment]
>pade remote desktop control should still be working through openfire plugin ?

Pade no more supports remote desktop control and there are no plans to add it back

**Comment by chuleta7** [comment]
Upppps, don't tell me that :( I had pinned my hopes on that solution because it doesn't need or depends  on a third party account service like teamviewer or anydesk wich you don't control and depends precisely on internet but instead a closed solution like Openfire wich works very well in our intranet only

Thanks anyway!
is it difficult to develop and bring back the remote desktop service ? I mean, if we can cooperate :)

**Comment by deleolajide** [comment]
You don't need to use Teamviewer anymore. There is now an open source alternative.

https://rustdesk.com/
