### ISSUE TITLE
Hide search functions of Padé / converse / admin console

### ISSUE THREAD

**Issue by jac110** [igniterealtime/pade#249]
Hello,

I'm building a private openfire community in which users and rooms are preset. 
I'd like to control the 'search' functions of users, directories and rooms in the admin console, converse and Padé.

For instance:
- can I hide the 'Search User Directory' icon of the converse toolbar ?

![image](https://user-images.githubusercontent.com/52374540/103021572-a864b200-454a-11eb-902b-ab878ceef894.png)

- can I hide or limit the 'search menu' in the settings of Padé?

![image](https://user-images.githubusercontent.com/52374540/103021663-ce8a5200-454a-11eb-9ff5-8f28d43b6488.png)

Many thanks for your return & congrats for the latest releases of Padé!

Best rgds,
Jacques

**Comment by deleolajide** [comment]
Added a new setting called enableDirectorySearch.
![image](https://user-images.githubusercontent.com/110731/103282149-b55f2680-49cc-11eb-9f80-e2c90766a961.png)

When false, removes search in options page.
![image](https://user-images.githubusercontent.com/110731/103282068-70d38b00-49cc-11eb-92aa-059ce592809c.png)

and in toolbars

![image](https://user-images.githubusercontent.com/110731/103282446-b6448800-49cd-11eb-8db2-f86663a74f78.png)


In branding file, add a setting for enableDirectorySearch and disable if you don't want uses to access it.
```
    enableDirectorySearch   : {disable: true, value: false},
```

**Comment by jac110** [comment]
Thank you Dele, that's exactly the kind of options I was chasing for :)
Kind regards,
Jacques

**Comment by Ityumenev** [comment]
> Спасибо Деле, именно такие варианты я и искал :) С уважением, Жак

please, help. How can I remove buttons in Pade.? For example, the Emoticons button in the chat or the Jitsi conference.
