### ISSUE TITLE
Contact feature

### ISSUE THREAD

**Issue by alveox** [igniterealtime/Pade#3]
I've trying pade with my server that contain 500+ ldap user, it would be great if pade have option to show online user only and also have basic user search feature.

**Comment by deleolajide** [comment]
Thanks for the feature request. I have done basic search in version 0.1.8 and will add add the option to select only online users in version 0.1.9

![image](https://user-images.githubusercontent.com/110731/33421879-76990454-d5ab-11e7-86c2-4280ef29b41f.png)

**Comment by deleolajide** [comment]
Online users only option now availble in version 0.1.9

![image](https://user-images.githubusercontent.com/110731/33437846-151ff206-d5e1-11e7-994d-a612104a2642.png)
