### ISSUE TITLE
Make Openfire Fastpath support compatible with WebMeet

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/Pade#30]
WebMeet now supports Openfire Fastpath using a [conversation form](https://space10-community.github.io/conversational-form/landingpage/).  Modify Pade to close any active groupchat window from the host before opening a new one.

**Comment by marclaporte** [comment]
This is fantastic!

This is on our wish list:
http://wikisuite.org/item66-Add-a-Chatbot-to-WikiSuite

**Comment by deleolajide** [comment]
The conversation form from is a really cool feature. It dynamically converts any HTML form into a conversation between a user and a bot.  The collected data can be sent server-side for processing. In the case of WebMeet, it is used as meta data to initiate a fastpath session. If an agent using Pade responds to the desktop notification, then converse.js is invoked to handle the MUC conversation. 

The cherry on top of the cake is that in the agent uusing Pade can push interactive H5P content to the web visitor and get immediate realtime accessment while in conversation.

![image](https://user-images.githubusercontent.com/110731/41104198-bc6c5566-6a62-11e8-9372-64803869c1ce.png)

This is now available in version 0.4.8
