### ISSUE TITLE
FAQ: How to configure Pade for my Openfire server

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/Pade#33]
In order to determine the server **hostname:port** and **domain name** for your openfire server, do the following.

Login into your openfire server and go to the Server Information page to get the domain name and hostname

![image](https://user-images.githubusercontent.com/110731/41817705-475cea54-7798-11e8-8b07-564afd08db2a.png)

To get the HTTP server port, goto the HTTP Bind Settings page

![image](https://user-images.githubusercontent.com/110731/41817735-bbba973e-7798-11e8-9412-8094b8be5e8e.png)

In this example, domain name is **traderlynk.4ng.net** and hostname is **traderlynk.4ng.net:7443**

![image](https://user-images.githubusercontent.com/110731/41817765-1edb801c-7799-11e8-97bd-cee4944c3ed9.png)

**Comment by marclaporte** [comment]
I suppose doc team should move this to https://igniterealtime.github.io/Pade/ ?

**Comment by deleolajide** [comment]
That sounds like a good plan. They raise questions/issues/queries here and then reuse the content in the documentation.

**Comment by Kishiko** [comment]
Just an additional info to this useful How-to, **HTTP Bind Settings** page is located in **Server Settings** tab, then hit **Http Binding** option.
![openfire-connection-credentials](https://user-images.githubusercontent.com/29162210/41818855-ec518cea-77b6-11e8-953c-7e929e11d450.PNG)

PS: I'm using the latest version, Openfire 4.2.3

**Comment by deleolajide** [comment]
Without any error messages or screenshot, there is no way to help you

**Comment by RobT111** [comment]
Dele,
I added the extension into chrome. Under server i added server.domain:7443 and also tried server.domain:7070.
Tried it with websockets on and off. Log in is the same as I use for Inverse and Converse.

I get no error, it simply says please wait...

**Comment by deleolajide** [comment]
I assume you have a valid certificate. It only works with TLS because of WebRTC. If you only have a self-signed certificate, then you will have to open the URL https://server.domain:7443 in a chrome tab and force the browser to accept your certificate like this

![image](https://user-images.githubusercontent.com/110731/49603083-28c71300-f982-11e8-81d9-c7446411f95d.png)

**Comment by deleolajide** [comment]
See https://github.com/igniterealtime/Pade/issues/66
