### ISSUE TITLE
Screen Sharing still require domain whitelisting?

### ISSUE THREAD

**Issue by klou** [igniterealtime/Pade#36]
Does Screen Sharing still require domain whitelisting and publishing a custom version of the extension?

I also found this: https://github.com/muaz-khan/getScreenId -- which apparently works around it (with a companion webrtc extension).

**Comment by deleolajide** [comment]
Pade does not require domain white-listing. It works with any domain because it is already a Chrome Extension. The generic method used by muaz khan does not work with jitsi-meet
