### ISSUE TITLE
When i click on logo nothing appear

### ISSUE THREAD

**Issue by rinorusso** [igniterealtime/Pade#5]
Hi, when i click on pade logo nothing appear with or without settings external domain

**Comment by deleolajide** [comment]
Sorry, there is no public service for Pade. You need to setup your own Openfire Meetings server.

Pade needs an Openfire meetings server with ofmeet, offocus and bookmarks plugins.  You then need to create some meeting/conference bookmarks that Pade will use.

You will get best results with the[ Etherlynk plugins](https://github.com/Traderlynk/ofmeet-openfire-plugin/releases).

**Comment by rinorusso** [comment]
Wow Etherlynk plugins works great!!! Thanks
