### ISSUE TITLE
UX issues

### ISSUE THREAD

**Issue by IzzabelleM** [igniterealtime/Pade#50]
Add Room button doesnt look like Add, looks like groups or contact button
()you could just put a simple + sign next to titles of Groups and Contacts)

**Comment by IzzabelleM** [comment]
Once I hit info button, info displays on a row that is hidden under row name

**Comment by IzzabelleM** [comment]
its not obvious which chatroom i am in

**Comment by IzzabelleM** [comment]
avatars as Initials capitals letters: are blurry + could have random colours assigned insteas of grey

**Comment by IzzabelleM** [comment]
when you click on Close group, the arrow also should be clikable

**Comment by IzzabelleM** [comment]
its not clear how to filter the contacts... maybe put 2 dropdown side by side? Its confusing having icons to the right that change something to their left...

**Comment by deleolajide** [comment]
>Add Room button doesnt look like Add
Fixed in converse 4.0.1

>Once I hit info button, info displays on a row that is hidden under row name
Fixed in converse 4.0.1

>Maybe add a bgcolor on the row to the left
Fixed in converse 4.0.1

>avatars as Initials capitals letters: are blurry + could have random colours assigned insteas of grey
Fixed in Pade version 0.5.2

>having the trash icon next to the contact.. isnt it too much? I would put it in the profile of the person..
Fixed in converse 4.0.1
