### ISSUE TITLE
Issues from WikiFest2018

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/Pade#51]
The following issues were identified during WikiFest2018

~1. Upgrade Converse from 4.0.0 alpha to 4.0.0 final~
~2. Add ability of audio/video recording tool to capture screen as well.~
~3. Modify the main icon button UI to popup the options button if connection is OFF~
~4. Prompt user to confirm jitsi-meet and hp5 content delivery~
~5. Give Pade generated avatars random colors~
~6. Add support for image pasting into input textbox using httpfileupload~

**Comment by marclaporte** [comment]
For #2: Ideally, to be able to get part of the screen like we did for the old https://sourceforge.net/projects/jcapture-applet/

**Comment by deleolajide** [comment]
7. Add support for image pasting into input textbox using httpfileupload

**Comment by deleolajide** [comment]
Fixed in version 0.5.1

**Comment by deleolajide** [comment]
Footnote on pasting feature 6 above

If an image is pasted, then the image auto-uploaded using converse. If an Open Graph (og) web page URL is pasted, then the page is scraped and the title, description and first image URL are fetched and added to the input box to produce something like this:

https://github.com/conversejs

Converse.js
https://avatars0.githubusercontent.com/u/37398988 
Web-based XMPP/Jabber chat client written in JavaScript - Converse.js
