### ISSUE TITLE
How to use Blogger and 'Message Blast' apps in Pàdé?

### ISSUE THREAD

**Issue by Kishiko** [igniterealtime/Pade#52]
In the options settings, I 've enabled both Blogger and 'Message Blast' apps but when I launch it, I get this error message: 

> HTTP ERROR 404
> Reason: Not found

How to get it to work?

**Comment by deleolajide** [comment]
You need the chatapi  plugin from https://github.com/igniterealtime/openfire-chat/releases installed on your openfire server

**Comment by deleolajide** [comment]
You also need the Solo blogger plugin for openfire - https://github.com/igniterealtime/Solo/releases

**Comment by Kishiko** [comment]
'Message Blast' is working now after installing those plugins on the server. But I still get the error message for Blogger after getting one Blogger blog out there. I'm wondering: Should I be the owner of a blog -- on Blogger -- to put in the 'Blog Name' input box?

**Comment by deleolajide** [comment]
>But I still get the error message for Blogger 

Ignore blogger for now. There is some outstanding work to be done to it before it can be installed on your Openfire server correctly.
