### ISSUE TITLE
Make triangle icon usable

### ISSUE THREAD

**Issue by rodrigolzd** [igniterealtime/Pade#58]
The grouping triangle icon should be clickable and just as functional as the text, it seems more natural to use the icon as a control to expand and collapse the lists.

**Comment by deleolajide** [comment]
Agreed. A PR to fix this is most welcome

**Comment by luciash** [comment]
This can be closed, right?

**Comment by deleolajide** [comment]
Yes, thanks

**Comment by luciash** [comment]
Ah, sorry, the triangle icon is still not toggleable on click... oops :) I thought the issue was actually the opposite (text not clickable to toggle).

**Comment by rodrigolzd** [comment]
so, this is going to be open again?

**Comment by luciash** [comment]
@deleolajide When I click the triangle I get in the Chrome DevTools console:
```
Uncaught TypeError: Cannot read property 'classList' of null
    at child.toggleRoomsList (converse.js:58793)
    at wrapper (converse.js:13440)
    at HTMLDivElement.handler (converse.js:1005)
  | toggleRoomsList | @ | converse.js:58793
  | wrapper | @ | converse.js:13440
  | handler | @ | converse.js:1005

```
