### ISSUE TITLE
Users rights status

### ISSUE THREAD

**Issue by rodrigolzd** [igniterealtime/Pade#59]
I find unnecessary to have the users rights in the room to be show with the full wording. It is too large. Perhaps just and image or the initial of the status if you must have it. O = Owner, M = Moderator. A mouse hover over the icon/letter should indicate what it means

There is no need to show the "Member" status, its just polution, if it must show this type of status, it should show that someone is not a member.

**Comment by deleolajide** [comment]
>I find unnecessary to have the users rights in the room to be show with the full wording

Good suggestion. A Pull Request (PR) is most welcome to fix this.

>There is no need to show the "Member" status, its just pollution

It depends on the purpose of the room. In a members-only room, I agree. In a public room, then it is the opposite and you will still get pollution.
