### ISSUE TITLE
Provide instructions on hosting "apps" on openfire's web server

### ISSUE THREAD

**Issue by jeremydrake-eAc** [igniterealtime/Pade#6]
Openfire has a web server on :7070 (and :7443).  Given that the readme for "apps" directory says to deploy them on "any web server" it seems like it would be handy to be able to deploy them onto the openfire web server.

Unfortunately I don't know enough about how openfire works to be able to figure out where to drop the files to have them be hosted, but I know that plugins such as Candy are able to do it.  It would be nice if somebody provided instructions or a ready-made plugin to host these within openfire.  Extra credit if the plugin also creates the required url bookmarks automatically.

**Comment by deleolajide** [comment]
Cool suggestion. 

The location for root folder of Openfire's web server at 7070/7443 is 
````
OPENFIRE_HOME/resource/spank
````

The chatapi plugin has a REST API for most openfire admin tasks including CRUD on bookmarks, so it could be the starting point to add the ability to upload web applications as zip files and expand them into the correct location and create a URL bookmark to access them.

**Comment by marclaporte** [comment]
@jeremydrake-eAc  Sorry for using this thread but I can't find your email anywhere. Are you near London by any chance?   http://wikisuite.org/2018-XMPP-WebRTC-and-JMAP-Hackathons-in-London

**Comment by deleolajide** [comment]
This is now implemented and available in version 0.3.1
