### ISSUE TITLE
Turn Features Panel into a smaller column of icons

### ISSUE THREAD

**Issue by rodrigolzd** [igniterealtime/Pade#60]
The features panel is too large, perhaps the options could be reduced to a single column of icons on the far right. Take a look at the example link: https://imgur.com/mJC42Z1

**Comment by deleolajide** [comment]
It is a good suggestion, but I personally prefer the features panel horizontally just above the input text box. I dislike having to move the mouse cursor far right to select a feature. If this was a responsive app that ran on mobile devices, then I would agree with you.

Also, the features panel is used by plugins to extend the features of Converse. There is more space horizontally than vertically before the need to scroll. 

If you feel very strongly about this feature request, I suggest you raise an issue directly [on Converse.](https://github.com/conversejs/converse.js/issues)
