### ISSUE TITLE
Improve password security

### ISSUE THREAD

**Issue by jeremydrake-eAc** [igniterealtime/Pade#7]
I generally don't store passwords in browsers.  I would like the ability to not store my password, but rather be prompted for it when needed.  I tried leaving the password field in the options blank, but that didn't work.

Also, if the user does opt to store their password, it should be stored at least obfuscated (probably stored using the same mechanism as stored passwords for websites are stored in the browser).  I discovered that the password is currently stored 'in the clear' in a localstorage sqlite-based database.

**Comment by deleolajide** [comment]
Totally agree. The current implementation of is just a stop gap and I am heading to client certificates issued by Openfire during user enrolment. In the meantime, asking for the password on demand or encrypting the stored password and very good suggestions and any Pull Requests will be very much appreciated.

**Comment by jeremydrake-eAc** [comment]
@deleolajide 
>  I am heading to client certificates issued by Openfire during user enrolment.

I am a little concerned about how that will play out when using LDAP.  In our environment, users don't enroll with Openfire, they just appear there when their LDAP account is created, on people's rosters according to their groups in LDAP.  The LDAP access that Openfire has is read-only.

**Comment by deleolajide** [comment]
Passwordless clients is [where](https://opkode.com/blog/strophe_converse_sasl_external/) I am heading specifically. I plan to extend the work started by [jcbrand](https://github.com/jcbrand). 

To use Pade, a user will have to download and install the openfire issued client certificate in their browser. Independent of whatever Openfire user/auth provider is in use, users would have still to perform this enrolment task.

**Comment by deleolajide** [comment]
> I discovered that the password is currently stored 'in the clear' in a localstorage sqlite-based database.

Did you actually access the password from another application? 

The password is stored in the clear in localstorage (not sqlite), but only JS from the chrome extension or the chrome developer console can access it.

**Comment by deleolajide** [comment]
Added a [stop gap solution](https://github.com/igniterealtime/Pade/commit/ff253938e7ff8b440f9cf736fb0e04c4c9d6cc79) to address the issue of storing the password in cleartext

**Comment by deleolajide** [comment]
![mtls](https://user-images.githubusercontent.com/110731/36793369-25c59782-1c95-11e8-8f8d-39a107275e0c.png)

I finally, got to MTLS authentication with no passwords stored or transmitted, compliments of a client certificate on desktop and server certificate in Openfire. The use credentials are encrypted into the client certificate. In future, we can add user entitlements to the certificate.

![totp](https://user-images.githubusercontent.com/110731/36793529-8cb31c30-1c95-11e8-8eca-1b14998534c0.png)

On the way, I stopped to implement a Time based One-Time Password (TOTP) option as well. This requires the use of the FreeOTP or Google Authenticator app on a mobile phone to generate the TOTP. Normally used for 2FA (two-factor authentication), I am using it to remove the need to store the password in local storage. The password is only used to generate the QR code for the mobile phone app and never stored on the phone or desktop.

**Comment by jeremydrake-eAc** [comment]
what plugin is required in openfire for the TOTP option?  I get a 404 error from the QR code button.  I see mention of OfChat in the options page, but the only thing I could find with that name was a chrome extension from like 4 years ago.

**Comment by deleolajide** [comment]
ofchat is now an openfire plugin that is part of my fork of openfire meetings

https://github.com/Traderlynk/ofmeet-openfire-plugin/releases/tag/v0.9.3-release3

**Comment by deleolajide** [comment]
The implementation of improved security is now done and available in version 0.3.1
