### ISSUE TITLE
Auto add converse as a sidecar panel to community web app

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/Pade#75]
When the Community web app is opened, use the Pade web extension content page to inject JavaScript that provides a sidecar for Converse into the web page.  use the [Gitter sidecar](https://gitlab.com/gitlab-org/gitter/sidecar) library to implement this.

**Comment by deleolajide** [comment]
This now available in version 0.6.0. This will only be applied when Community web application is enabled,  Converse web is disabled and Sidecar is enabled.

![image](https://user-images.githubusercontent.com/110731/46802671-e6a09d00-cd55-11e8-8038-cf7dc5efa98a.png)

**Community web app with sidecar enabled**

![image](https://user-images.githubusercontent.com/110731/46802489-55c9c180-cd55-11e8-94a3-1ced5c8397c8.png)

**Sidecar in action**

![image](https://user-images.githubusercontent.com/110731/46802558-91648b80-cd55-11e8-80f7-d84ce0f17ccc.png)

**Comment by rodrigolzd** [comment]
Why is this so large?

**Comment by deleolajide** [comment]
>Why is this so large?

Because it is using the converse full-screen view.  The sidecar is designed to share the screen 50/50 with the web app. 

If you need a smaller chat panel,  then we could add an option for the standard converse view like the [tiki converse plugin](https://doc.tiki.org/XMPP) or the [wordpress converse plugin](https://wordpress.org/plugins/conversejs/) that works like the chat widget in LinkedIn.
