### ISSUE TITLE
1-click joining of XMPP rooms: Just a blue background

### ISSUE THREAD

**Issue by marclaporte** [igniterealtime/Pade#77]
URLs on http://wikisuite.org/XMPP-chatrooms#Openfire to 1-click join a chat room should work (they work in other clients)

I set the protocol handler:
<img width="516" alt="2018-10-12_134722" src="https://user-images.githubusercontent.com/1004261/46885235-65b0d680-ce25-11e8-8835-cadfa18ef402.png">

Yet, when I visit those links, I get
<img width="818" alt="2018-10-12_134350" src="https://user-images.githubusercontent.com/1004261/46885254-75c8b600-ce25-11e8-8e22-29839a104543.png">

**Comment by deleolajide** [comment]
Thanks for spotting that. Broken with converse latest code.

**Comment by deleolajide** [comment]
Fixed it and available in version 0.6.0. View was wrongly set to "mobile"
