### ISSUE TITLE
Collaboration Apps don't work with 1to1 chat

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/Pade#78]
With 1to1 chat, there is no echo back to the originator unlike MUC, consequently the UI is not refreshed.

**Comment by jcbrand** [comment]
This could perhaps be solved via XEP-0198 support.

The relevant ticket for Converse: https://github.com/conversejs/converse.js/issues/316

**Comment by deleolajide** [comment]
Fixed it in version 0.6.0. 

Decided to implement a client side solution without involving XMPP server. When collab events (mouse clicks, cursor & keyboard) are received from chrome extension listener for a 1to1 chat, the events are echoed back to chrome extension handler in addition to sending them to other participant.

![image](https://user-images.githubusercontent.com/110731/46909858-5dde5880-cf31-11e8-8d17-636ee9f32e6a.png)
