### ISSUE TITLE
Fix a number of UX issues

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/Pade#80]
Fix the following user experience issues:

1. ~Meeting invitations not working~
2.  ~Group chat invitation notifications pointing at the wrong room~
3. ~Branded logo not  displayed in Converse splash screen~
4. ~Add email to user directory search results~
5. ~Add an icon to Converse toolbar which opens Pàdé Options window in order to access the user directory and conversation search features~

**Comment by deleolajide** [comment]
Done and available in version 0.7.0

**Comment by deleolajide** [comment]
I cheated. They were mostly done before I raised the issue :-)

**Comment by marclaporte** [comment]
hahahhaha

An honest cheater :-)
