### ISSUE TITLE
Wrong room

### ISSUE THREAD

**Issue by robertokir** [igniterealtime/Pade#91]
Hi Guys,

In Chrome, there's the Pade extension icon. When I hover over it, it show "Pade@Work - evoludata-team (room)" - so far, so good. 
Then I click on it. A new window pops up, first showing a room with a long alphanumeric name (see image). Then it arrives at "luci's room", also showing the message "You are not on the member list of this groupchat.". And then I have to manually go to the room I really want.

Thanks!

![screenshot from 2018-11-12 18-53-45](https://user-images.githubusercontent.com/33861038/48370069-1ffb5e00-e6b0-11e8-95b3-a12f55df8f32.png)
![screenshot from 2018-11-12 18-53-51](https://user-images.githubusercontent.com/33861038/48370092-31446a80-e6b0-11e8-87fc-41696c8c6adf.png)

**Comment by deleolajide** [comment]
According to the openfire admin, the room with the long name is a members only room with no members registered. You will not be allowed into the room. I suspect you have a bookmark to the room with auto-join set to true causing the room to be opened and the join to fail everytime you start Converse from Pade.

**Solution**: Remove the bookmark

![image](https://user-images.githubusercontent.com/110731/48370530-892fa100-e6b1-11e8-81aa-715da357a18a.png)

**Comment by robertokir** [comment]
Hi Dele,

I did a Factory Reset as instructed. But it didn't work, can't get rid of
Luci's room or from arriving there by default. I've also tried removing and
re-adding the chrome extension, to no avail.

thanks
Roberto

**Comment by deleolajide** [comment]
Please ask Luci to delete the room if he does not use it any more. Let's see if that will make a difference.

**Comment by luciash** [comment]
Can be closed?

**Comment by deleolajide** [comment]
I think so
