### ISSUE TITLE
Display confirmation dialog with preview before pasting and uploading clipboard directly to chat

### ISSUE THREAD

**Issue by luciash** [igniterealtime/Pade#97]
Maybe display a modal window to preview and then confirm before calling the converse API to upload (to prevent accidental clipboard content/picture leak to the chat).

**Comment by deleolajide** [comment]
Good Idea!!

**Comment by deleolajide** [comment]
This should do it. Available in version 0.8.6

![image](https://user-images.githubusercontent.com/110731/49372702-7417c200-f6f3-11e8-90cd-062ce15c28cd.png)

**Comment by luciash** [comment]
@deleolajide perfect! Thanks man! (y)
