### ISSUE TITLE
User search

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/Pade#99]

**Comment by ClaudeStabile** [comment]
Openfire Room and user easy search feature is missing. Expected to be added, will help usage and quick adoption of Padé.

**Comment by ClaudeStabile** [comment]
Hi dele,

63 and 81 are fine to find users, what would help is having the list when you do a user add. But that's fine :) you can close this one

**Comment by deleolajide** [comment]
The search in #81 is actually for adding new contacts. If you click on the contact name with the blue hyperlink, the contact is added to Converse contacts roster.

**Comment by ClaudeStabile** [comment]
That's fine :) it works as expected, still discovering padé... :)
